### ISSUE TITLE
getting large objects is slow even with hint plain

### ISSUE THREAD

**Issue by kruczy** [LegendApp/legend-state#602]
Hi,

 When working with larger data sets it becomes very expensive to use observables for example in my case just  `observable(() => ObservableHint.plain(largeObject)).get()` takes ~300ms just to process the object inside legend even tho is wrapped in plain hint.

Wrapping in `ObservableHint.opaque` solves the issue of perf but breaks the ability to observe members of the object as legend will throw errors in that case.

I am pretty sure `ObservableHint.plain` worked before to let legend know not to traverse the object but maybe I hallucinated something

**Comment by jmeistrich** [comment]
I just checked and `plain` seems to be preventing it from processing the object. Can you share a repro?

I have this test to make sure plain works:

```ts
test('Lazy activation perf with plain hint', () => {
        const obj: Record<string, any> = {};
        const Num = 10000;
        for (let i = 0; i < Num; i++) {
            obj['key' + i] = {
                child: {
                    grandchild: {
                        value: 'hi',
                    },
                },
            };
        }

        const obs = observable(ObservableHint.plain(obj));

        const now = performance.now();
        obs.get();
        const then = performance.now();

        expect(then - now).toBeLessThan(1);
    });
```

It takes 9ms if I don't use plain, so it seems like it should be working?

**Comment by jmeistrich** [comment]
Oh awesome, thank you. I will fix that.

**Comment by kruczy** [comment]
just tested on my app and its not improved and if I change the test to make the observable like this: 
`observable(synced({ get: () => ObservableHint.plain(obj) }));` it still fails as before but passes with `observable(() => ObservableHint.plain(obj));`
